#!/usr/bin/env python

import sys

from rqt_lcm_logger.logger import Loggher
from rqt_gui.main import Main

plugin = 'rqt_lcm_logger'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))